# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_plan_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'userinfo',
                'verbose_name_plural': 'userinfo',
            },
        ),
    ]
