# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='date',
            new_name='birth',
        ),
    ]
